site_name: PowBot Mobile
site_url: https://docs.powbot.org/
extra_css:
  - assets/styles.css
theme:
  name: material
  logo: assets/images/pb_logo.png
  favicon: assets/favicon.ico
  font:
    code: Roboto Mono
  palette:
      scheme: slate
      primary: black
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
nav:
  - Home: index.md
  - Scripts: 'Scripts.md'
  - Guides:
      - 'Guides': 'Getting_Started/index.md'
      - 'Installation': 
        - 'Base Requirements': 'Getting_Started/install/index.md'
        - 'Devices': 
          - 'Device Requirements': 'Getting_Started/install/devices/index.md'
          - 'Installing PowBot': 'Getting_Started/install/devices/install.md'
        - 'Emulators': 
          - 'EmulatorRequirements': 'Getting_Started/install/emulators/index.md'
          - 'Bluestacks': 'Getting_Started/install/emulators/bluestacks.md'
          - 'LDPlayer': 'Getting_Started/install/emulators/ldplayer.md'
      - 'Logging': 'Getting_Started/Logging.md'
      - 'Proxy Setup':
          - 'RethinkDNS': 'Getting_Started/Proxy_Setup/Rethink.md'
          - 'SocksTun': 'Getting_Started/Proxy_Setup/SocksTun.md'
      - 'Jagex account setup': 'Getting_Started/TransferringToJagexAccount.md'

  - Development:
      - 'Dev Setup': 'Development/SettingUpDevelopmentEnv.md'
      - 'Using the API':
          - 'Bank': 'Development/API/BankAPI.md'
          - 'Chat': 'Development/API/ChatAPI.md'
          - 'Combat': 'Development/API/Combat.md'
          - 'Equipment': 'Development/API/EquipmentAPI.md'
          - 'Events': 'Development/API/Events.md'
          - 'Grand Exchange': 'Development/API/GrandExchangeAPI.md'
          - 'Ground Items': 'Development/API/GroundItems.md'
          - 'Items': 'Development/API/Items.md'
          - 'Locations': 'Development/API/Locations.md'
          - 'Magic': 'Development/API/MagicAPI.md'
          - 'NPC': 'Development/API/Npcs.md'
          - 'Objects': 'Development/API/Objects.md'
          - 'PaintBuilder': 'Development/API/PaintBuilderAPI.md'
          - 'Prayer': 'Development/API/PrayerAPI.md'
          - 'Rendering': 'Development/API/Rendering.md'
          - 'Skills': 'Development/API/SkillsAPI.md'
          - 'Store': 'Development/API/StoreAPI.md'
          - 'Varpbits': 'Development/API/Varpbits.md'
          - 'Waits/Sleep': 'Development/API/Waits.md'
          - 'Walking': 'Development/API/Walking.md'
          - 'Widgets': 'Development/API/Widgets.md'
          - 'World': 'Development/API/WorldHopping.md'

      - 'Quirks':
          - 'Interaction Types': 'Development/Quirks/InteractionTypes.md'
          - 'GroundItem Interactions': 'Development/Quirks/GroundItemInteractions.md'
          - 'Inventory Interactions': 'Development/Quirks/InventoryInteractions.md'
          - 'Npc Interactions': 'Development/Quirks/NpcInteractions.md'
          - 'Null Safety': 'Development/Quirks/NullSafety.md'
          - 'Object Interactions': 'Development/Quirks/ObjectInteractions.md'
          - 'Stream': 'Development/Quirks/StreamAPI.md'
          - 'Using Waits': 'Development/Quirks/UsingWaits.md'
          - 'Widget Interactions': 'Development/Quirks/WidgetInteracting.md'

      - 'Script Writers':
          - 'Ranks': 'Development/Script_Writers/ScriptWriterRanks.md'
  - Help & Support: 'Help_And_Support/temp.md'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Y8TGmMh47r

markdown_extensions:
  - codehilite
  - toc
  - tables
  - admonition
  - footnotes
  - abbr
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

copyright: RuneScape is a registered trademark of Jagex Ltd. | Use of PowBot and its services is not endorsed or recommended by Jagex Ltd.
